# Generated by Django 4.1.1 on 2023-07-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet", name="hide", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="snippet",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
